### ISSUE TITLE
Documentation or User Guide for UTAM-Java

### ISSUE THREAD

**Issue by radhikamanne** [salesforce/utam-java#35]
Can I please get documentation or a user guide that helps set up the utam compiler for the selenium java automation framework? The readme of the repo is providing instructions to set up the project but really doesn't speak about the instructions to use the framework. I am looking for steps to create a .json file, right path to create .json files, and how to use the compiler to create Page Objects.

Thank you in Advance!

**Comment by jimevanssfdc** [comment]
@radhikamanne Thanks for contacting us about this issue. The repository is in an early alpha state at the moment, so we do not have documentation available at present. It's a known gap, and one we'll be closing, but it won't be for some time as we aren't anticipating moving out of alpha releases for some time.

**Comment by radhikamanne** [comment]
I appreciate a lot for taking a moment and responding to my post @jimevanssfdc. I will revisit the repo later for any documentation updates.
